# Generated by Django 3.2 on 2022-03-14 06:21

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, unique=True)),
                ('desc_safe', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('color_code', models.CharField(default='#0a8ddf', max_length=10)),
            ],
        ),
    ]
