# Generated by Django 3.2 on 2022-03-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_replycomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
