# Generated by Django 3.2.11 on 2022-03-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_storylike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='num_participants',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
