# Generated by Django 3.2 on 2022-02-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220221_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='manage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='manage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
