# Generated by Django 3.2 on 2022-02-21 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220221_1422'),
    ]

    operations = [
        migrations.DeleteModel(
            name='manage',
        ),
    ]
