# Generated by Django 3.2 on 2022-03-05 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blog_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
    ]
