# Generated by Django 3.2 on 2022-03-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_blog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content_save',
            field=models.TextField(null=True),
        ),
    ]
