# Generated by Django 3.2 on 2022-03-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_blog_content_save'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='content_save',
        ),
        migrations.AddField(
            model_name='blog',
            name='content_safe',
            field=models.TextField(blank=True, null=True),
        ),
    ]
